"""Tests for autogenerated API."""

from derive_client.data_types.generated_models import (
    PrivateGetOrdersParamsSchema,
    PrivateGetOrdersResultSchema,
    PrivateGetSubaccountsParamsSchema,
    PrivateGetSubaccountsResultSchema,
)


def test_get_private_get_subaccounts(client_admin_wallet):
    wallet = client_admin_wallet._auth.wallet
    params = PrivateGetSubaccountsParamsSchema(wallet=wallet)
    result = client_admin_wallet._private_api.rpc.get_subaccounts(params=params)
    assert isinstance(result, PrivateGetSubaccountsResultSchema)


def test_get_private_get_orders(client_admin_wallet):
    subaccount_id = client_admin_wallet.active_subaccount.id
    params = PrivateGetOrdersParamsSchema(subaccount_id=subaccount_id)
    result = client_admin_wallet._private_api.rpc.get_orders(params=params)
    assert isinstance(result, PrivateGetOrdersResultSchema)
